### ISSUE TITLE
__wbindgen_add_to_stack_pointer is not a function

### ISSUE THREAD

**Issue by Innovgame** [PSeitz/lz4-wasm#2]
```js
 const wasm = await import('lz4-wasm');
 const data = wasm.compress(new Uint8Array([1, 2, 3]));
```

Uncaught (in promise) TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function

**Comment by PSeitz** [comment]
You can check the usage example here: https://github.com/PSeitz/lz4-wasm/blob/main/example_project

Maybe this also helps
https://stackoverflow.com/questions/72618553/how-to-import-a-wasm-module-in-wasm-rust-and-pass-a-string-parameter
